### ISSUE TITLE
Error component is missing 'type'

### ISSUE THREAD

**Issue by Querijn** [MingweiSamuel/riotapi-schema#1]
in the components array in `http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.json`, the first component schema `Error`, should have a `type`, alike other objects. It only contains `properties`.

**Comment by Querijn** [comment]
![afbeelding](https://user-images.githubusercontent.com/3397066/33239275-84c1c9f4-d29e-11e7-801a-35749c9faf37.png)
vs 
![afbeelding](https://user-images.githubusercontent.com/3397066/33239277-92db979a-d29e-11e7-9f97-6f18306243a5.png)

**Comment by MingweiSamuel** [comment]
👍 bc79237cd2f562741539d9c9e2a55cc43498994e
