### ISSUE TITLE
/lol/champion-mastery/v4/champion-masteries/by-puuid/{encryptedPUUID}/by-champion/{championId} seems to have lost type key for championId

### ISSUE THREAD

**Issue by Token07** [MingweiSamuel/riotapi-schema#49]
In 0ebaa34f the type field was removed underneath parameters. x-type is still present, though it now "integer" instead of "string"

**Comment by MingweiSamuel** [comment]
Fix deployed in https://github.com/MingweiSamuel/riotapi-schema/commit/4e9d11faeb4cf42b3dd0c47ecf2822f9a7d90174#diff-33a82c6fdb2653a6f2b66c9aa83f88db5dfa2eee8d2bf97521797a168f6a3387R613-R618
