### ISSUE TITLE
Summoner-v4 ByPUUID has `name` field that seems to not exist anymore

### ISSUE THREAD

**Issue by Soundofdarkness** [MingweiSamuel/riotapi-schema#50]
Hey !
Just as a quick heads up, your schema still has the name property of ByPUUID on Summoner-V4 which seems to be removed in the official documentation and seems to not be returned by the API anymore either.

Riot API Docs:
![image](https://github.com/MingweiSamuel/riotapi-schema/assets/14293048/71c33148-71c8-4603-9f95-58b00cf59455)

riotapi-schema:
![image](https://github.com/MingweiSamuel/riotapi-schema/assets/14293048/ab3a44e3-4a2d-453f-bafd-9f1f6ea53ebe)

Currently it seems like fetching summoners is broken on [Riven](https://github.com/MingweiSamuel/Riven/) as a result, however thats something im not 100% sure on as im just learning rust.

**Comment by MingweiSamuel** [comment]
b81b77be1ec31e653b398c9fcd3bc51b614607d4

**Comment by MingweiSamuel** [comment]
Released riven 2.40.0

**Comment by Soundofdarkness** [comment]
Thank you !
