### ISSUE TITLE
Missing regional proxies used by tournament API

### ISSUE THREAD

**Issue by Derpthemeus** [MingweiSamuel/riotapi-schema#6]
The tournament API uses the host `americas.api.riotgames.com`, which is not listed in the available platforms.

Reference: https://developer.riotgames.com/regional-endpoints.html

**Comment by MingweiSamuel** [comment]
Alright, should be an easy fix to add, taking a look now

**Comment by MingweiSamuel** [comment]
I'm considering adding
```
servers = [{
    url: 'https://americas.api.riotgames.com'
}]
```
(or similar) to each of the tournament endpoints which would override the default server platforms. Botty would need to be updated to check this field I assume

**Comment by MingweiSamuel** [comment]
I decided not to take this route and add them all to the global server variables. there's now a `x-platforms-available` field to show which endpoints are available per method

so this should be working for botty as soon as everything updates

**Comment by MingweiSamuel** [comment]
Note that this means botty will parse incorrect requests going to americas.api.riotgames.com for other endpoints (for now)
